require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
-- spec "user.none-ls"
spec "user.illuminate"
spec "user.gitsigns"
spec "user.whichkey"
spec "user.nvimtree"
-- spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.harpoon"
spec "user.neotest"
spec "user.autopairs"
spec "user.neogit"
spec "user.alpha"
spec "user.project"
spec "user.indentline"
spec "user.toggleterm"
spec "user.extras.copilot"
spec "user.extras.pounce"
spec "user.extras.tabout"
spec "user.extras.trouble"
spec "user.extras.surround"
spec "user.extras.emmet"
spec "user.extras.git-conflict"
spec "user.extras.lsp-lightbulb"
spec "user.extras.outline"
spec "user.extras.vs-tasks"
spec "user.extras.scrollbar"
spec "user.extras.dressing"
spec "user.extras.cellular-automaton"
spec "user.extras.notify"
-- spec "user.extras.auto-format"
spec "user.extras.conform"
-- spec "user.extras.time-tracker"
require "user.lazy"
